<?php

namespace AppBundle\Repository;

/**
 * CategorieCentreInteretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCentreInteretRepository extends \Doctrine\ORM\EntityRepository
{
}
