<?php

namespace AppBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FairePartiStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
