<?php

namespace AppBundle\Repository;

/**
 * ThemePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemePageRepository extends \Doctrine\ORM\EntityRepository
{
}
