<?php

namespace AppBundle\Repository;

/**
 * TypeGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeGroupeRepository extends \Doctrine\ORM\EntityRepository
{

}
